version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: validator
  coins:
  - 2000000000uaeth
  - 100000000000uatom
  - 100000000000bnb
  mnemonic: equip town gesture square tomorrow volume nephew minute witness beef rich 
  gadget actress egg sing secret pole winter alarm law today check violin uncover
- name: evm-faucet
  coins:
  - 1000000000uaeth
  mnemonic: hundred flash cattle inquiry gorilla quick enact lazy galaxy apple 
  bitter liberty print sun hurdle oak town cash because round chalk marriage 
  response success
- name: user
  coins:
  - 1000000000uaeth
  - 1000000000usdx
- name: relayer
  mnemonic: never reject sniff east arctic funny twin feed upper series stay shoot
   vivid adapt defense economy pledge fetch invite approve ceiling admit gloom exit
faucet:
  name: faucet
  coins: 
  - 1000000000uaeth
  - 100000000000uatom
  - 100000000000bnb
  host: 0.0.0.0:4500

