version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: validator
  coins:
  - 2000000000uaeth
  - 100000000000uatom
  - 100000000000bnb
  staked: 1000000000uaeth
  address: aeth1ffv7nhd3z6sych2qpqkk03ec6hzkmufyhnk5h0
  mnemonic: equip town gesture square tomorrow volume nephew minute witness beef rich 
  gadget actress egg sing secret pole winter alarm law today check violin uncover
- name: evmfaucet
  coins:
  - 1000000000uaeth
  address: aeth18jz5lyhhy6ncjlyty064kttw93yzaulqxnr9ft
  mnemonic: hundred flash cattle inquiry gorilla quick enact lazy galaxy apple 
  bitter liberty print sun hurdle oak town cash because round chalk marriage 
  response success
- name: user
  coins:
  - 1000000000uaeth
  - 1000000000usdx
  address: aeth10wlnqzyss4accfqmyxwx5jy5x9nfkwh6ctzhhu
  mnemonic: news tornado sponsor drastic dolphin awful plastic select true 
  lizard width idle ability pigeon runway lift oppose isolate maple aspect safe 
  jungle author hole
- name: relayer
  coins: 
  - 1000000000uaeth 
  address: aeth15tmj37vh7ch504px9fcfglmvx6y9m706d29g9u
  mnemonic: never reject sniff east arctic funny twin feed upper series stay shoot
   vivid adapt defense economy pledge fetch invite approve ceiling admit gloom exit
faucet:
  name: faucet
  coins: 
  - 1000000000uaeth
  - 100000000000uatom
  - 100000000000bnb
  host: 0.0.0.0:4500

