version: '3'

services:
  aethnode0:
    container_name: aethnode0
    image: "networks/local/aethnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-aeth.log}
    volumes:
      - ./build:/aeth:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  aethnode1:
    container_name: aethnode1
    image: "networks/local/aethnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-aeth.log}
    volumes:
      - ./build:/aeth:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  aethnode2:
    container_name: aethnode2
    image: "networks/local/aethnode"
    environment:
      - ID=2
      - LOG=${LOG:-aeth.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/aeth:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  aethnode3:
    container_name: aethnode3
    image: "networks/local/aethnode"
    environment:
      - ID=3
      - LOG=${LOG:-aeth.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/aeth:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
